
packages:
  - !include common.yaml

substitutions:
  # user configuration
  bulb_power_rating: 5.0
  update_period_default: 180 s


debug:
  update_interval: ${update_period_default}


light:
  - id: !extend ${light_id}
    on_state:
      - sensor.template.publish:
          id: power_draw_est
          state: !lambda |-
            const float quiescent_pwr_draw = 0.3;

            std::string effect_name = id(${light_id}).get_effect_name();
            float mult = 0.0;

            if (effect_name == "Pulse (low, fast)") {
                mult = 0.2;
            } else if (effect_name == "Pulse (low, slow)") {
                mult = 0.2;
            } else if (effect_name == "Pulse (high, fast)") {
                mult = 0.8;
            } else if (effect_name == "Pulse (high, slow)") {
                mult = 0.8;
            } else if (effect_name == "Pulse (full, fast)") {
                mult = 0.5;
            } else if (effect_name == "Pulse (full, slow)") {
                mult = 0.5;
            } else {  // flicker
                float brightness = id(${light_id}).remote_values.get_brightness();
                float gamma_correct = id(${light_id}).get_gamma_correct();

                id(${light_id}).remote_values.as_brightness(&brightness, gamma_correct);
                mult = std::acos(1 - (2 * brightness)) / 3.14159;  // RMS power compensation
            }

            ESP_LOGV("light", "Multiplier: %0.4f; bulb power rating: %0.4f", mult, id(bulb_power_rating_input).state);
            return (mult * id(bulb_power_rating_input).state) + quiescent_pwr_draw;

sensor:
  - platform: template
    id: power_draw_est
    name: "Power [est]"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: "mdi:flash"
    accuracy_decimals: 1
    update_interval: never


### Configuration ---


number:
  - platform: template
    id: default_transition_length_input
    name: "Transition length"
    icon: "mdi:clock-start"
    entity_category: config
    unit_of_measurement: ms
    mode: auto
    device_class: duration
    min_value: 0
    max_value: 3000
    step: 100
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 300
    set_action:
      - lambda: |-
          id(${light_id}).set_default_transition_length(x);

  - platform: template
    id: minimum_power_input
    name: "Minimum level"
    icon: "mdi:lightbulb-on-10"
    entity_category: config
    unit_of_measurement: "%"
    mode: auto
    min_value: 0
    max_value: 99
    step: 1
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    set_action:
      - output.set_min_power:
          id: ${ac_dimmer_id}
          min_power: !lambda "return (float)x / 100.0f;"
      - light.turn_on:
          id: ${light_id}
          brightness: 1 %
          transition_length: 0 s

  - platform: template
    id: gamma_correct_input
    name: "Gamma correct"
    icon: "mdi:gamma"
    entity_category: config
    mode: auto
    min_value: 0.5
    max_value: 4
    step: 0.25
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: ${gamma_correct}
    set_action:
      - lambda: |-
          id(${light_id}).set_gamma_correct(x);
      - light.turn_on:
          id: ${light_id}

  - platform: template
    id: bulb_power_rating_input
    name: "Bulb power rating"
    icon: "mdi:flash"
    entity_category: config
    unit_of_measurement: "W"
    mode: box
    device_class: power
    min_value: 0.5
    max_value: 200
    step: 0.1
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: ${bulb_power_rating}


select:
  - platform: template
    id: restore_mode_input
    name: "Restore mode"
    icon: "mdi:backup-restore"
    entity_category: config
    options:
      - "Off"
      - "On"
    update_interval: never
    optimistic: true
    restore_value: true
    initial_option: "Off"
    set_action:
      - lambda: |-
          std::string option = x.c_str();

          LightRestoreMode res_mode = LIGHT_ALWAYS_OFF;
          if (option == "Off") {
            res_mode = LIGHT_ALWAYS_OFF;
          } else if (option == "On") {
            res_mode = LIGHT_ALWAYS_ON;
          } else {
            ESP_LOGW("select", "Unknown select option: %s\n", option);
          }

          ESP_LOGV("main", "Restore mode index: %d\n", res_mode);

### Configuration ---


button:
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: config
    device_class: restart

text_sensor:
  - platform: version
    name: "ESPHome version"
    hide_timestamp: true

  - platform: debug
    reset_reason:
      name: "Reset reason"
